{"uuid":"e997f2d7-71c3-483d-80b3-7e61e33c9fdb","historyId":"e5270bd1568033b35b9a86ed7c4791d0","testCaseId":"[engine:junit-jupiter]/[class:test.AgendamentoTest]/[method:criarAgendamentoComExcecaoBloqueio()]","testCaseName":"criarAgendamentoComExcecaoBloqueio()","fullName":"test.AgendamentoTest.criarAgendamentoComExcecaoBloqueio","labels":[{"name":"junit.platform.uniqueid","value":"[engine:junit-jupiter]/[class:test.AgendamentoTest]/[method:criarAgendamentoComExcecaoBloqueio()]"},{"name":"host","value":"PMO-6410"},{"name":"thread","value":"42180@PMO-6410.main(1)"},{"name":"framework","value":"junit-platform"},{"name":"language","value":"java"},{"name":"package","value":"test.AgendamentoTest"},{"name":"testClass","value":"test.AgendamentoTest"},{"name":"testMethod","value":"criarAgendamentoComExcecaoBloqueio"},{"name":"suite","value":"test.AgendamentoTest"}],"links":[],"name":"criarAgendamentoComExcecaoBloqueio()","status":"broken","statusDetails":{"known":false,"muted":false,"flaky":false,"message":"Ação falhou após nova tentativas","trace":"java.lang.RuntimeException: Ação falhou após nova tentativas\r\n\tat utils.Actions.executarAcaoComTentativas(Actions.java:45)\r\n\tat utils.Actions.clicarBotaoPegandoPeloCss(Actions.java:54)\r\n\tat pages.AgendamentoPage.excecaoAgenda(AgendamentoPage.java:259)\r\n\tat pages.AgendamentoPage.criarAgendamentoExcecao(AgendamentoPage.java:416)\r\n\tat test.AgendamentoTest.criarAgendamentoComExcecaoBloqueio(AgendamentoTest.java:158)\r\n\tat java.base/java.lang.reflect.Method.invoke(Method.java:568)\r\n\tat java.base/java.util.ArrayList.forEach(ArrayList.java:1511)\r\n\tat java.base/java.util.ArrayList.forEach(ArrayList.java:1511)\r\n"},"stage":"finished","description":"","steps":[],"attachments":[],"parameters":[],"start":1733923835045,"stop":1733923942175}